### ISSUE TITLE
function "uniform_neg_sampling"

### ISSUE THREAD

**Issue by lihuiliullh** [ralphabb/BoxE#1]
what is the purpose of 'arities_tiled' in "uniform_neg_sampling"?
Is it possible that some elements in 'arities_tiled' is 0, and 'replacement_choice = tf.floormod(replacement_choice, arities_tiled)' gets error, like 'InvalidArgumentError: Integer division by zero [Op:FloorMod]'?

**Comment by ralphabb** [comment]
arities_tiled is intended to compute how many entities are connected in a fact, and tile it to all the negative samples. Basically, you need the arity of every fact you're trying to sample a negative fact for, so that you can sample a position at which you replace the entity. It should not be possible to get replacement by zero, as all facts have at least one entity, and therefore arity is at least one unless your input data is malformed.
